### ISSUE TITLE
wersja probna ktora nie jest na githubie jest zepsuta 

### ISSUE THREAD

**Issue by Bekaa0668** [Cukrowydomek964/aqua#1]
no ta wersja probna o ktorej tylko chb ja slyszalem ma problem ze jak z glownego robie na inny (z glownego na download client lub view coolest people in server) to sie psuje i nie da zmienic
![image](https://github.com/user-attachments/assets/e14ca797-e5ac-409b-a5e0-e0cfff835e2f)

**Comment by Cukrowydomek964** [comment]
Ale ta która na githubie jest działa więc w czym problem
